{
  "openapi": "3.0.0",
  "info": {
    "title": "devops-notepad-api",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:5000"
    },
    {
      "url": "http://localhost:3000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "name": "Oluseyi Adeegbe",
                "email": "examplemail@gmail.com",
                "password": "@password1"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "success": true,
                  "message": "signup successful",
                  "user": {
                    "name": "Oluseyi Adeegbe",
                    "email": "examplemail@gmail.com",
                    "password": "$2b$10$bl32ojHP586GgmeQjd635eyiQQKL6N6LT44wt7QeZ14x92F01udG2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "ExaMpleMail@gmail.com",
                "password": "@password1"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "email_verified": {
                          "type": "number"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      }
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Logged in Successfully",
                  "user": {
                    "id": "(UUID())",
                    "name": "Oluseyi Adeegbe",
                    "email": "examplemail@gmail.com",
                    "email_verified": 0,
                    "created_at": "2022-12-02T00:41:00.000Z",
                    "updated_at": "2022-12-02T00:41:00.000Z"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IihVVUlEKCkpIiwiZW1haWwiOiJleGFtcGxlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE2Njk5NDE2NjEsImV4cCI6MTY2OTk0NTI2MX0.Gt7MIpVwpyDxVUFJtLGFuBT0ZN2_PEV7kPYSc9bX_co"
                }
              }
            }
          }
        }
      }
    },
    "/server/(UUID())/notifications": {
      "post": {
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "log": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "log": "add data points"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "serverLog": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": true,
                  "message": "successful",
                  "serverLog": "add data points"
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "notifications": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "serverId": {
                            "type": "string"
                          },
                          "log": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    },
                    "page": {
                      "type": "number"
                    }
                  }
                },
                "example": {
                  "success": true,
                  "notifications": [
                    {
                      "id": "(UUID())",
                      "serverId": "(UUID())",
                      "log": "add data points",
                      "created_at": "2022-12-02T00:41:01.000Z",
                      "updated_at": "2022-12-02T00:41:01.000Z"
                    }
                  ],
                  "page": 1
                }
              }
            }
          }
        },
        "requestBody": {}
      }
    },
    "/server": {
      "get": {
        "description": "",
        "tags": [],
        "parameters": [
          {
            "in": "query",
            "name": "device",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "currentPage": {
                      "type": "number"
                    },
                    "limit": {
                      "type": "number"
                    },
                    "servers": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "ipAddress": {
                            "type": "string"
                          },
                          "deviceId": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "success": true,
                  "message": "1 servers found on this device",
                  "currentPage": 1,
                  "limit": 12,
                  "servers": [
                    {
                      "id": "(UUID())",
                      "name": "example server",
                      "ipAddress": "google.com",
                      "deviceId": "80988579",
                      "created_at": "2022-12-02T00:41:00.000Z",
                      "updated_at": "2022-12-02T00:41:00.000Z"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "patch": {
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "id": "(UUID())",
                "name": "updated server name"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": true,
                  "message": "Server updated successfully"
                }
              }
            }
          }
        }
      }
    },
    "/server/delete": {
      "post": {
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "serverIds": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              },
              "example": {
                "serverIds": [
                  "(UUID())"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "message": {
                      "type": "string"
                    },
                    "result": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "success": true,
                  "message": "servers deleted successfully",
                  "result": "1 servers deleted!"
                }
              }
            }
          }
        }
      }
    }
  }
}